name: CI Workflow

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build Docker Image
        run: docker build -t myapp .

      - name: Run container
        run: docker run -d -p 8080:80 myapp

      - name: wait for container
        run: sleep 5

      - name: check output
        run: curl http://localhost:8080 